package workable.movieRama.utils;

public enum ResponseCode {
    REQUEST_SUCCESS,
    REQUEST_ERROR,
    AUTH_FAILED,
    VOTE_UPDATED,
    VOTE_CREATED,
    MISSING_HEADERS,
    VOTE_NOT_FOUND,
    VOTE_WAS_DELETED,
    REGISTER_USER_EXISTS,
    USER_CANNOT_VOTE_SELF_CREATED_MOVIE,
    REGISTER_USER_FAILED,
    INVALID_USER
}

